env:
  global:
  - REPO=d1ablorus/masscan
  - TAG=v0.4

services:
  - docker

script:
  - docker build -t $REPO .;
  - docker tag $REPO:latest $REPO:$TAG;
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $REPO;
  - docker push $REPO:$TAG;
